import type { ItemEstoque } from "@/lib/types";

export const itensEstoque: ItemEstoque[] = [
  // ===== CONSUMO - ALIMENTOS =====
  {
    id: "e1",
    nome: "Arroz tipo 1",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 42,
    unidade: "kg",
    pontoReposicao: 30,
    custoUnitario: 7.5,
    fornecedor: "Distribuidora Bom Preço",
    validade: "2026-12-30",
  },
  {
    id: "e2",
    nome: "Feijão carioca",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 18,
    unidade: "kg",
    pontoReposicao: 25,
    custoUnitario: 9.8,
    fornecedor: "Distribuidora Bom Preço",
    validade: "2026-10-15",
  },
  {
    id: "e3",
    nome: "Leite integral 1L",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 24,
    unidade: "L",
    pontoReposicao: 40,
    custoUnitario: 5.9,
    fornecedor: "Laticínios Vila Nova",
    validade: "2026-06-20",
  },
  {
    id: "e4",
    nome: "Pão francês",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 80,
    unidade: "un",
    pontoReposicao: 50,
    custoUnitario: 0.75,
    fornecedor: "Padaria Madalena",
    validade: "2026-06-12",
  },
  {
    id: "e5",
    nome: "Achocolatado em pó 400g",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 12,
    unidade: "un",
    pontoReposicao: 8,
    custoUnitario: 9.9,
    fornecedor: "Atacadão Central",
    validade: "2027-03-10",
  },
  {
    id: "e6",
    nome: "Iogurte natural 170g",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 30,
    unidade: "un",
    pontoReposicao: 50,
    custoUnitario: 2.3,
    fornecedor: "Laticínios Vila Nova",
    validade: "2026-06-15",
  },
  {
    id: "e7",
    nome: "Banana prata",
    categoria: "Consumo",
    subcategoria: "Alimentos",
    quantidade: 8,
    unidade: "kg",
    pontoReposicao: 15,
    custoUnitario: 6.5,
    fornecedor: "Hortifruti Ceasa",
    validade: "2026-06-13",
  },

  // ===== CONSUMO - LIMPEZA =====
  {
    id: "e8",
    nome: "Detergente neutro 500ml",
    categoria: "Consumo",
    subcategoria: "Limpeza",
    quantidade: 24,
    unidade: "un",
    pontoReposicao: 12,
    custoUnitario: 3.2,
    fornecedor: "Atacadão Central",
  },
  {
    id: "e9",
    nome: "Álcool 70% 1L",
    categoria: "Consumo",
    subcategoria: "Limpeza",
    quantidade: 6,
    unidade: "L",
    pontoReposicao: 10,
    custoUnitario: 12.9,
    fornecedor: "Atacadão Central",
  },
  {
    id: "e10",
    nome: "Papel toalha pacote",
    categoria: "Consumo",
    subcategoria: "Limpeza",
    quantidade: 22,
    unidade: "un",
    pontoReposicao: 15,
    custoUnitario: 6.5,
    fornecedor: "Atacadão Central",
  },
  {
    id: "e11",
    nome: "Sabão em pó 1kg",
    categoria: "Consumo",
    subcategoria: "Limpeza",
    quantidade: 4,
    unidade: "un",
    pontoReposicao: 8,
    custoUnitario: 16.9,
    fornecedor: "Atacadão Central",
  },

  // ===== CONSUMO - MATERIAL PEDAGÓGICO =====
  {
    id: "e12",
    nome: "Resma de papel A4",
    categoria: "Consumo",
    subcategoria: "Material Pedagógico",
    quantidade: 18,
    unidade: "un",
    pontoReposicao: 10,
    custoUnitario: 28.9,
    fornecedor: "Papelaria Escolar Plus",
  },

  // ===== VENDA - UNIFORMES =====
  {
    id: "e20",
    nome: "Camiseta uniforme manga curta",
    categoria: "Venda",
    subcategoria: "Uniforme",
    quantidade: 18,
    unidade: "un",
    pontoReposicao: 10,
    custoUnitario: 28.0,
    precoVenda: 59.9,
    fornecedor: "Confecções Brasil",
    tamanho: "P",
  },
  {
    id: "e21",
    nome: "Camiseta uniforme manga curta",
    categoria: "Venda",
    subcategoria: "Uniforme",
    quantidade: 25,
    unidade: "un",
    pontoReposicao: 12,
    custoUnitario: 28.0,
    precoVenda: 59.9,
    fornecedor: "Confecções Brasil",
    tamanho: "M",
  },
  {
    id: "e22",
    nome: "Camiseta uniforme manga curta",
    categoria: "Venda",
    subcategoria: "Uniforme",
    quantidade: 19,
    unidade: "un",
    pontoReposicao: 12,
    custoUnitario: 28.0,
    precoVenda: 59.9,
    fornecedor: "Confecções Brasil",
    tamanho: "G",
  },
  {
    id: "e23",
    nome: "Bermuda uniforme",
    categoria: "Venda",
    subcategoria: "Uniforme",
    quantidade: 22,
    unidade: "un",
    pontoReposicao: 10,
    custoUnitario: 25.0,
    precoVenda: 54.9,
    fornecedor: "Confecções Brasil",
    tamanho: "M",
  },
  {
    id: "e24",
    nome: "Agasalho uniforme",
    categoria: "Venda",
    subcategoria: "Uniforme",
    quantidade: 14,
    unidade: "un",
    pontoReposicao: 8,
    custoUnitario: 62.0,
    precoVenda: 129.9,
    fornecedor: "Confecções Brasil",
    tamanho: "M",
  },

  // ===== VENDA - FESTA =====
  {
    id: "e30",
    nome: "Kit Festa Junina (chapéu + lenço)",
    categoria: "Venda",
    subcategoria: "Festa",
    quantidade: 35,
    unidade: "un",
    pontoReposicao: 20,
    custoUnitario: 8.5,
    precoVenda: 24.9,
    fornecedor: "Festas Decor Ltda.",
  },
  {
    id: "e31",
    nome: "Camiseta Festa Família",
    categoria: "Venda",
    subcategoria: "Festa",
    quantidade: 28,
    unidade: "un",
    pontoReposicao: 15,
    custoUnitario: 18.0,
    precoVenda: 49.9,
    fornecedor: "Confecções Brasil",
  },
  {
    id: "e32",
    nome: "Lembrancinha Dia das Mães",
    categoria: "Venda",
    subcategoria: "Festa",
    quantidade: 12,
    unidade: "un",
    pontoReposicao: 5,
    custoUnitario: 6.0,
    precoVenda: 19.9,
    fornecedor: "Artesã Maria Helena",
  },

  // ===== VENDA - MATERIAL ESCOLAR =====
  {
    id: "e40",
    nome: "Caderno de desenho personalizado",
    categoria: "Venda",
    subcategoria: "Material Escolar",
    quantidade: 16,
    unidade: "un",
    pontoReposicao: 10,
    custoUnitario: 8.5,
    precoVenda: 24.9,
    fornecedor: "Papelaria Escolar Plus",
  },
];

export const itensAbaixoPontoReposicao = itensEstoque.filter(
  (i) => i.quantidade <= i.pontoReposicao
);

export const itensValidadeProxima = itensEstoque.filter((i) => {
  if (!i.validade) return false;
  const dias = (new Date(i.validade).getTime() - Date.now()) / (1000 * 60 * 60 * 24);
  return dias <= 14;
});
