import type { KanbanCard, KanbanColuna } from "@/lib/types";

export const colunasKanbanPadrao: KanbanColuna[] = [
  { id: "c-todo", nome: "A Fazer", cor: "#94a3b8" },
  { id: "c-doing", nome: "Em Andamento", cor: "#3b82f6" },
  { id: "c-review", nome: "Revisão", cor: "#a855f7" },
  { id: "c-done", nome: "Concluído", cor: "#22c55e" },
];

export const cardsKanban: KanbanCard[] = [
  // Jardim II - A (t5)
  {
    id: "k1",
    colunaId: "c-todo",
    turmaId: "t5",
    titulo: "Preparar projeto 'Animais da Fazenda'",
    descricao: "Selecionar livros, montar painel temático e atividades de pintura.",
    tipo: "Atividade",
    prazo: "2026-06-15",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k2",
    colunaId: "c-todo",
    turmaId: "t5",
    titulo: "Avaliação bimestral — Leitura",
    descricao: "Aplicar atividade individual de identificação de letras e sílabas.",
    tipo: "Avaliação",
    prazo: "2026-06-20",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k3",
    colunaId: "c-doing",
    turmaId: "t5",
    titulo: "Ensaio Festa Junina",
    descricao: "Coreografia da quadrilha — 3 ensaios por semana.",
    tipo: "Evento",
    prazo: "2026-06-22",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k4",
    colunaId: "c-doing",
    turmaId: "t5",
    titulo: "Acompanhamento individual — Heitor",
    descricao: "Reforço em escrita silábica conforme orientação da coordenação.",
    tipo: "Pendência",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k5",
    colunaId: "c-review",
    turmaId: "t5",
    titulo: "Portfólio bimestral",
    descricao: "Revisar com a coordenação antes do envio aos pais.",
    tipo: "Atividade",
    prazo: "2026-06-18",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k6",
    colunaId: "c-done",
    turmaId: "t5",
    titulo: "Reunião de pais bimestral",
    descricao: "Realizada em 05/06. Boa adesão das famílias.",
    tipo: "Evento",
    responsavel: "Profa. Mariana Costa",
  },
  {
    id: "k7",
    colunaId: "c-done",
    turmaId: "t5",
    titulo: "Projeto Dia das Mães",
    descricao: "Lembrancinhas entregues, painel montado.",
    tipo: "Atividade",
    responsavel: "Profa. Mariana Costa",
  },

  // 1º Ano - A (t7)
  {
    id: "k10",
    colunaId: "c-todo",
    turmaId: "t7",
    titulo: "Avaliação de Matemática — Adição até 20",
    tipo: "Avaliação",
    prazo: "2026-06-18",
    responsavel: "Profa. Cláudia Martins",
  },
  {
    id: "k11",
    colunaId: "c-doing",
    turmaId: "t7",
    titulo: "Projeto Leitura — 'O Pequeno Príncipe'",
    descricao: "Leitura coletiva e atividades de interpretação.",
    tipo: "Atividade",
    prazo: "2026-06-30",
    responsavel: "Profa. Cláudia Martins",
  },
  {
    id: "k12",
    colunaId: "c-doing",
    turmaId: "t7",
    titulo: "Visita à biblioteca municipal",
    tipo: "Evento",
    prazo: "2026-06-19",
    responsavel: "Profa. Cláudia Martins",
  },
  {
    id: "k13",
    colunaId: "c-done",
    turmaId: "t7",
    titulo: "Ditado bimestral",
    tipo: "Avaliação",
    responsavel: "Profa. Cláudia Martins",
  },

  // 2º Ano - A (t9)
  {
    id: "k20",
    colunaId: "c-todo",
    turmaId: "t9",
    titulo: "Saída pedagógica — Museu",
    tipo: "Evento",
    prazo: "2026-06-25",
    responsavel: "Profa. Luciana Souza",
  },
  {
    id: "k21",
    colunaId: "c-doing",
    turmaId: "t9",
    titulo: "Produção textual — Conto inventado",
    tipo: "Atividade",
    prazo: "2026-06-17",
    responsavel: "Profa. Luciana Souza",
  },
];
