import type { Turma } from "@/lib/types";

export const turmas: Turma[] = [
  {
    id: "t1",
    nome: "Berçário - A",
    serie: "Berçário",
    turno: "Integral",
    professorId: "p1",
    professorNome: "Profa. Vanessa Oliveira",
    totalAlunos: 8,
    capacidade: 10,
    cor: "#fb923c",
  },
  {
    id: "t2",
    nome: "Maternal I - A",
    serie: "Maternal I",
    turno: "Manhã",
    professorId: "p2",
    professorNome: "Profa. Carolina Ribeiro",
    totalAlunos: 12,
    capacidade: 15,
    cor: "#f97316",
  },
  {
    id: "t3",
    nome: "Maternal II - A",
    serie: "Maternal II",
    turno: "Manhã",
    professorId: "p3",
    professorNome: "Profa. Patrícia Lima",
    totalAlunos: 14,
    capacidade: 16,
    cor: "#facc15",
  },
  {
    id: "t4",
    nome: "Jardim I - A",
    serie: "Jardim I",
    turno: "Manhã",
    professorId: "p4",
    professorNome: "Profa. Beatriz Sousa",
    totalAlunos: 18,
    capacidade: 20,
    cor: "#84cc16",
  },
  {
    id: "t5",
    nome: "Jardim II - A",
    serie: "Jardim II",
    turno: "Manhã",
    professorId: "p5",
    professorNome: "Profa. Mariana Costa",
    totalAlunos: 20,
    capacidade: 22,
    cor: "#22c55e",
  },
  {
    id: "t6",
    nome: "Jardim II - B",
    serie: "Jardim II",
    turno: "Tarde",
    professorId: "p6",
    professorNome: "Profa. Renata Almeida",
    totalAlunos: 19,
    capacidade: 22,
    cor: "#10b981",
  },
  {
    id: "t7",
    nome: "1º Ano - A",
    serie: "1º Ano",
    turno: "Manhã",
    professorId: "p7",
    professorNome: "Profa. Cláudia Martins",
    totalAlunos: 22,
    capacidade: 25,
    cor: "#06b6d4",
  },
  {
    id: "t8",
    nome: "1º Ano - B",
    serie: "1º Ano",
    turno: "Tarde",
    professorId: "p8",
    professorNome: "Prof. Rodrigo Pereira",
    totalAlunos: 21,
    capacidade: 25,
    cor: "#0ea5e9",
  },
  {
    id: "t9",
    nome: "2º Ano - A",
    serie: "2º Ano",
    turno: "Manhã",
    professorId: "p9",
    professorNome: "Profa. Luciana Souza",
    totalAlunos: 23,
    capacidade: 25,
    cor: "#3b82f6",
  },
  {
    id: "t10",
    nome: "3º Ano - A",
    serie: "3º Ano",
    turno: "Manhã",
    professorId: "p10",
    professorNome: "Profa. Adriana Ferreira",
    totalAlunos: 24,
    capacidade: 26,
    cor: "#6366f1",
  },
  {
    id: "t11",
    nome: "4º Ano - A",
    serie: "4º Ano",
    turno: "Manhã",
    professorId: "p11",
    professorNome: "Prof. Eduardo Santos",
    totalAlunos: 22,
    capacidade: 26,
    cor: "#8b5cf6",
  },
  {
    id: "t12",
    nome: "5º Ano - A",
    serie: "5º Ano",
    turno: "Manhã",
    professorId: "p12",
    professorNome: "Profa. Fernanda Dias",
    totalAlunos: 25,
    capacidade: 26,
    cor: "#a855f7",
  },
];

// Turmas que o "Professor" logado vê (mock - assumimos professorId p5 e p7)
export const turmasDoProfessor: string[] = ["t5", "t7"];

export function getTurma(id: string): Turma | undefined {
  return turmas.find((t) => t.id === id);
}
