import type { Venda } from "@/lib/types";

export const vendas: Venda[] = [
  {
    id: "v1",
    data: "2026-06-08",
    itemNome: "Camiseta uniforme M",
    tipo: "Uniforme",
    quantidade: 2,
    precoUnitario: 59.9,
    total: 119.8,
    cliente: "Mariana Almeida (resp. Sofia)",
    alunoId: "a1",
    formaPagamento: "Pix",
    notaFiscal: "NF-2026/0245",
  },
  {
    id: "v2",
    data: "2026-06-07",
    itemNome: "Kit Festa Junina",
    tipo: "Evento/Festa",
    quantidade: 4,
    precoUnitario: 24.9,
    total: 99.6,
    cliente: "Camila Pereira (resp. Heitor)",
    alunoId: "a2",
    formaPagamento: "Cartão",
    notaFiscal: "NF-2026/0244",
  },
  {
    id: "v3",
    data: "2026-06-07",
    itemNome: "Agasalho uniforme M",
    tipo: "Uniforme",
    quantidade: 1,
    precoUnitario: 129.9,
    total: 129.9,
    cliente: "Patrícia Costa (resp. Manuela)",
    alunoId: "a3",
    formaPagamento: "Pix",
    notaFiscal: "NF-2026/0243",
  },
  {
    id: "v4",
    data: "2026-06-06",
    itemNome: "Camiseta Festa Família",
    tipo: "Evento/Festa",
    quantidade: 3,
    precoUnitario: 49.9,
    total: 149.7,
    cliente: "Daniela Carvalho (resp. Bernardo)",
    alunoId: "a8",
    formaPagamento: "Cartão",
    notaFiscal: "NF-2026/0242",
  },
  {
    id: "v5",
    data: "2026-06-05",
    itemNome: "Almoço extra (semana)",
    tipo: "Alimentação",
    quantidade: 5,
    precoUnitario: 32.0,
    total: 160.0,
    cliente: "Juliana Oliveira (resp. Davi)",
    alunoId: "a4",
    formaPagamento: "Boleto",
  },
  {
    id: "v6",
    data: "2026-06-05",
    itemNome: "Camiseta uniforme G",
    tipo: "Uniforme",
    quantidade: 2,
    precoUnitario: 59.9,
    total: 119.8,
    cliente: "Tatiana Ferreira (resp. Alice)",
    alunoId: "a11",
    formaPagamento: "Pix",
    notaFiscal: "NF-2026/0241",
  },
  {
    id: "v7",
    data: "2026-06-04",
    itemNome: "Bermuda uniforme M",
    tipo: "Uniforme",
    quantidade: 1,
    precoUnitario: 54.9,
    total: 54.9,
    cliente: "Aline Rocha (resp. Valentina)",
    alunoId: "a7",
    formaPagamento: "Dinheiro",
  },
  {
    id: "v8",
    data: "2026-06-03",
    itemNome: "Lembrancinha Dia das Mães",
    tipo: "Evento/Festa",
    quantidade: 2,
    precoUnitario: 19.9,
    total: 39.8,
    cliente: "Cíntia Dias (resp. Maria Júlia)",
    alunoId: "a13",
    formaPagamento: "Pix",
  },
  {
    id: "v9",
    data: "2026-06-02",
    itemNome: "Almoço extra (semana)",
    tipo: "Alimentação",
    quantidade: 5,
    precoUnitario: 32.0,
    total: 160.0,
    cliente: "Bianca Pinto (resp. Lorenzo)",
    alunoId: "a10",
    formaPagamento: "Pix",
  },
  {
    id: "v10",
    data: "2026-06-01",
    itemNome: "Caderno de desenho personalizado",
    tipo: "Material",
    quantidade: 4,
    precoUnitario: 24.9,
    total: 99.6,
    cliente: "Fabiana Cardoso (resp. Liz)",
    alunoId: "a15",
    formaPagamento: "Cartão",
    notaFiscal: "NF-2026/0240",
  },
];

export const totalVendasMes = vendas.reduce((acc, v) => acc + v.total, 0);
